# Generated by Django 4.1.3 on 2022-11-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_ad_image_alter_ad_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="media/"),
        ),
    ]
